---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: "Install docker"
      become: true
      yum:
        name: docker
        state: present

    - name: "Install python3-pip"
      become: true
      yum:
        name: python3-pip
        state: present
        
    - name: "Setup docker service"
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: "Upgrade pip"
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3

    - name: "Install python requirements"
      pip:
        chdir: .
        requirements: requirements.txt

    - name: "Install Eclipse Mosquitto Docker Image"
      become: yes
      ansible.builtin.shell: docker pull eclipse-mosquitto
